#!/bin/bash

# ...

while getopts ":hv" opt; do
  case $opt in
    h|\-h) print_help && exit 0 ;;
    v|\-v) echo "Version 1.0" && exit 0 ;;
    d|\-d) debug_mode=true && exit 0 ;;
    \?) error_handler "Invalid option: -$opt" ;;
  esac
done

# ...

if [ "$debug_mode" = true ]; then
  # Enable debug mode and print out more detailed information
  echo "Debug mode enabled..."
fi
